### ISSUE TITLE
Support for C++14

### ISSUE THREAD

**Issue by JGMonroy** [mrpt-ros-pkg/pose_cov_ops#1]
Hello,
After updating to MRPT 1.9 I think this pkg also needs to add the CMake header to compile against C++14, right?

set (CMAKE_CXX_STANDARD 14)  # Require C++14

If you prefer I can make a pull-request.

**Comment by jlblancoc** [comment]
Sure! Yes please, go open it 👍

**Comment by jlblancoc** [comment]
Please, also note that since recent commits (yesterday!), both 1.5.4 and
2.0 branches of mrpt expose a similar API for smart pointers, so the ros
pcks code should be compatible with both versions.
