### ISSUE TITLE
Apply TF2/geometry_msgs Transform to PoseWithCovariance

### ISSUE THREAD

**Issue by roncapat** [mrpt-ros-pkg/pose_cov_ops#11]
While something totally doable by encoding desired transform as a Pose and using this library, it would be great to directly apply transformations via TF2.

**Comment by jlblancoc** [comment]
Do you mean... offering something like this? 

```cpp
void compose(const PoseWithCovariance &a, const tf2::geometry_msgs::Transform &b,
             PoseWithCovariance &out);
```

**Comment by roncapat** [comment]
Exactly :)

**Comment by jlblancoc** [comment]
I think 2f72b8519d97a2e6998c5c00539f5f1be26c75b7 now does it. 
Cheers.
