### ISSUE TITLE
kinetic release of pose_cov_ops fails to build on debian due to too new version of cmake

### ISSUE THREAD

**Issue by tfoote** [mrpt-ros-pkg/pose_cov_ops#4]
It's requiring cmake 3.1 or higher, but jessie has 3.0.2

http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__pose_cov_ops__debian_jessie_amd64__binary/58/console

```
23:09:07    debian/rules override_dh_auto_configure
23:09:07 make[1]: Entering directory '/tmp/binarydeb/ros-kinetic-pose-cov-ops-0.1.7'
23:09:07 # In case we're installing to a non-standard location, look for a setup.sh
23:09:07 # in the install tree that was dropped by catkin, and source it.  It will
23:09:07 # set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
23:09:07 if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi && \
23:09:07 dh_auto_configure -- \
23:09:07 	-DCATKIN_BUILD_BINARY_PACKAGE="1" \
23:09:07 	-DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
23:09:07 	-DCMAKE_PREFIX_PATH="/opt/ros/kinetic"
23:09:07 	mkdir -p obj-x86_64-linux-gnu
23:09:07 	cd obj-x86_64-linux-gnu
23:09:07 	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic -DCMAKE_PREFIX_PATH=/opt/ros/kinetic
23:09:07 CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
23:09:07   CMake 3.1 or higher is required.  You are running version 3.0.2
23:09:07 
23:09:07 
```

This is causing other mrpt packages to fail to build: 
![image](https://user-images.githubusercontent.com/447804/34686869-d2e1896e-f461-11e7-8dc3-d331ae725eb8.png)

Potential solutions: 
- Roll back release
- Lower required version of cmake
- blacklist package: if the cmake version cannot be lowered this package can be blacklisted to prevent the buildfarm from trying to build it.

**Comment by jlblancoc** [comment]
Thanks! I'm curious about the deadline for this issue on your side?
I want to fix this asap, but on the other hand we're working on a big refactoring inside MRPT and ideally all ROS nodes will have to be updated *after* such refactoring ends (perhaps a *few* days from today). 

If the next ROS release is imminent, I could just apply a quick fix to this package alone and that'll be enough!

**Comment by tfoote** [comment]
The next kinetic sync is imminent (today): https://discourse.ros.org/t/preparing-for-kinetic-sync-2018-01-08/3627/1 We're in a testing freeze and this is the only regression flagged currently. If you don't believe that there are active users on Jessie you could let this regression stand for this sync and once it's fixed it can be restored in the next sync with the refactor.

**Comment by jlblancoc** [comment]
It should be fixed now! Sorry for the blocking...

It's tested in both a local machine and on travis+docker. 
bloom-release is running right now so expect a PR against rosdistro within minutes. 
Thanks again!
