### ISSUE TITLE
Debian package not found on Ubu 16.04 64Bits

### ISSUE THREAD

**Issue by Axel13fr** [mrpt-ros-pkg/pose_cov_ops#5]
Hi,
I run apt install ros-kinetic-pose-cov-ops on a regular basis to build docker images. All of a sudden, the packaged stopped being found without any changes in my build recipe.

Any change the deb package would be missing somehow ? I'm now building from source as a workaround...

**Comment by jlblancoc** [comment]
The last update of kinetic packages by the osrf guys caught us in the middle of some refactoring and the package was removed from the release. But it's fixed now, the package must re appear on the next kinetic update... they usually update once a month or so.

**Comment by Axel13fr** [comment]
Thank you for your quick response. I guess this is the same issue for other mrpt packages ?

**Comment by jlblancoc** [comment]
Exactly!
